#!/bin/bash
TARGET="/home/drew/tmp/drewhughlett"
GIT_DIR="/home/drew/code/drewhughlett.git"
BRANCH="main"

while read oldrev newrev ref
do
	# only checking out the main (or whatever branch you would like to deploy)
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
		filelist=$(git diff-tree --no-commit-id --name-only -r $newrev)
		echo "Ref $ref received. Deploying ${BRANCH} branch to production"

		mkdir -p $TARGET
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
		cd $TARGET

    echo "Building and starting Docker services"
		docker-compose down && docker-compose up --build -d 
		cd /
		rm -rf $TARGET

	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done