#!/bin/bash
TARGET="/home/drew/tmp/drewhughlett"
GIT_DIR="/home/drew/code/drewhughlett.git"
BRANCH="main"
CONTAINER_NAME="drewhughlettsite"
IMAGE_NAME="site"

while read oldrev newrev ref
do
	# only checking out the main (or whatever branch you would like to deploy)
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
		filelist=$(git diff-tree --no-commit-id --name-only -r $newrev)
		echo "Ref $ref received. Deploying ${BRANCH} branch to production..."

		mkdir -p $TARGET
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
		cd $TARGET && cd drew-hughlett-site

    echo "Building new Docker image"
		docker build -f Dockerfile -t $IMAGE_NAME .
		cd /
		rm -rf $TARGET

		# echo "Redeploying UI..."
		if [ "$(docker ps -qa -f name=$CONTAINER_NAME)" ]; then
			echo "Found container - $CONTAINER_NAME"
			if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
				echo "Stopping running container - $CONTAINER_NAME"
				docker stop $CONTAINER_NAME;
			fi
			echo "Removing stopped container - $CONTAINER_NAME"
			docker rm $CONTAINER_NAME;
		fi

    docker run -d --name=$CONTAINER_NAME -p 80:80 $IMAGE_NAME
	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done